---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-app-deployment
spec:
  replicas: 2        
  selector:                 
    matchLabels:               
      app: product-app  
  template:               
    metadata:                  
      labels:                  
        app: product-app  
    spec:                      
      containers:
      - name: product-app-1.0.0
        image: arboulahdour/nodejs-product:1.0.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: product-app-svc
  labels:
    app: product-app
spec:
  type: NodePort
  selector:
    app: product-app
  ports:
  - port: 8800
    nodePort: 30000
    targetPort: 3000
